{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "dir_run": { "type": "string", "default": "./" },
    "map_fastq": { "type": "boolean", "default": true },
    "mapper": { "type": "string", "minLength": 1, "enum": ["minimap2"], "default": "minimap2"},
    "caller": {
      "type": "object",
      "properties": {
        "cutesv": { "type": "boolean", "default": true },
        "severus": { "type": "boolean", "default": true },
        "sniffles": { "type": "boolean", "default": true },
        "svim": { "type": "boolean", "default": true },
        "svision": { "type": "boolean", "default": true },
        "debreak": { "type": "boolean", "default": true },
        "delly": { "type": "boolean", "default": true },
        "nanosv": { "type": "boolean", "default": true },
        "nanovar": { "type": "boolean", "default": true }
      },
      "minProperties": 1
    },
    "type_sv": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["BND", "DEL", "INS", "INV", "DUP"]
      },
      "minItems": 1,
      "default": ["BND", "DEL", "INS", "INV", "DUP"]
    },
    "threads": { "type": "integer", "minimum": 1, "default": 10 },
    "libs_r": { "type": "array", "items": { "type": "string" }, "minItems": 1 },
    "fasta": { "type": "string" },
    "index_minimap2": { "type": "string" },
    "dir_data": { "type": "string" },
    "suffix_fastq": { "type": "string" },
    "bed_tandem_repeats": { "type": "string" },
    "min_num_reads": { "type": "integer", "minimum": 1, "default": 3 },
    "min_length_reads": { "type": "integer", "minimum": 1, "default": 1000 },
    "min_quality_mapping": { "type": "integer", "minimum": 1, "default": 20 },
    "min_coverage": { "type": "integer", "minimum": 1, "default": 6 },
    "min_length_sv": { "type": "integer", "minimum": 1, "default": 100 },
    "min_dhffc": { "type": "number", "minimum": 0, "default": 0.7 },
    "max_dhbfc": { "type": "number", "minimum": 0, "default": 1.3 },
    "merge_distance_sv": {
      "type": "object",
      "properties": {
        "BND": { "type": "integer", "minimum": 1, "default": 10 },
        "DEL": { "type": "integer", "minimum": 1, "default": 10 },
        "INS": { "type": "integer", "minimum": 1, "default": 10 },
        "INV": { "type": "integer", "minimum": 1, "default": 10 },
        "DUP": { "type": "integer", "minimum": 1, "default": 10 }
      },
      "minProperties": 1
    },
    "merge_nbr_callers": {
      "type": "object",
      "properties": {
        "BND": { "type": "integer", "minimum": 1, "default": 3 },
        "DEL": { "type": "integer", "minimum": 1, "default": 3 },
        "INS": { "type": "integer", "minimum": 1, "default": 3 },
        "INV": { "type": "integer", "minimum": 1, "default": 3 },
        "DUP": { "type": "integer", "minimum": 1, "default": 3 }
      },
      "minProperties": 1
    },
    "merge_type_sv": {
      "type": "object",
      "properties": {
        "BND": { "type": "boolean" },
        "DEL": { "type": "boolean" },
        "INS": { "type": "boolean" },
        "INV": { "type": "boolean" },
        "DUP": { "type": "boolean" }
      },
      "minProperties": 1
    },
    "merge_strand": {
      "type": "object",
      "properties": {
        "BND": { "type": "boolean" },
        "DEL": { "type": "boolean" },
        "INS": { "type": "boolean" },
        "INV": { "type": "boolean" },
        "DUP": { "type": "boolean" }
      },
      "minProperties": 1
    },
    "merge_estimate_distance": {
      "type": "object",
      "properties": {
        "BND": { "type": "boolean" },
        "DEL": { "type": "boolean" },
        "INS": { "type": "boolean" },
        "INV": { "type": "boolean" },
        "DUP": { "type": "boolean" }
      },
      "minProperties": 1
    },
    "genome": { "type": "string", "minLength": 1, "enum": ["GRCh37", "GRCh38"] },
    "version_cache_snpeff": { "type": "integer" },
    "version_cache_vep": { "type": "integer" },
    "dir_db_snpeff": { "type": "string" },
    "dir_db_vep": { "type": "string" },
    "config_nanosv": { "type": "string" },
    "bed_nanosv": { "type": "string" },
    "model_clair3": { "type": "string" },
    "bed_nvtr": { "type": "string" },
    "model_svision": { "type": "string" }
  },
  "additionalProperties": false
}