software-deployment-method:
  - apptainer
  - conda
apptainer-args: "--bind /storage,/home/user"
conda-prefix: /.snakemake/envs/smk_sv
scheduler: greedy
printshellcmds: True
keep-incomplete: True
cores: all
resources:
  mem_mb: 500000  # 500GB
default-resources:
  mem_mb: 10000  # 10GB
set-threads:
  annotate_sv_snpeffnvep: 10
  annotsv: 10
  filter_sv_annotation: 10
  filter_sv: 10
  clair3: 10
  cutesv: 10
  debreak: 10
  nanosv: 10
  nanovar: 10
  severus: 10
  snpeff: 10
  sniffles: 10
  svision: 10
  minimap2: 10
  minimap2_index: 10
  vep: 10
set-resources:
  snpeff:
    mem_mb: 50000
  svision:
    runtime: 72h
