rule extract_annotations:
    conda:
        "../../envs/bcftools.yaml"
    input:
        vep="{caller}/{sample}/{caller}.{type_sv}.vep.vcf",
        snpeff="{caller}/{sample}/{caller}.{type_sv}.snpeff.vcf",
        vcf="{caller}/{sample}/{caller}.{type_sv}.vcf",
        survivor="survivor/{sample}/{sample}.{type_sv}.merged.vcf",
    output:
        tab="survivor/{sample}/{sample}.{caller}.{type_sv}.tab",
        ids=touch(temp("survivor/{sample}/{caller}.{type_sv}.id")),
        vep="{caller}/{sample}/merged/{caller}.{type_sv}.vep.vcf",
        snpeff="{caller}/{sample}/merged/{caller}.{type_sv}.snpeff.vcf",
        vcf="{caller}/{sample}/merged/{caller}.{type_sv}.vcf",
    params:
        callers=CALLERS,
    log:
        "logs/{sample}/extract_annotations.{caller}.{type_sv}.log",
    script:
        "../../scripts/extract_annotations.sh"
