pep_version: 2.1.0
sample_table: "samples.csv"
sample_modifiers:
  append:
    ONT_fastq_dir: /home/user/projects/SV/data/wgs
    ONT_fastq: key
  derive:
    attributes: [ONT_fastq]
    sources:
      key: "{ONT_fastq_dir}/{sample_name}.fq.gz"
